# Generated by Django 4.2.1 on 2023-05-13 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logger',
            name='link',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logger',
            name='status',
            field=models.CharField(default='error', max_length=255),
            preserve_default=False,
        ),
    ]
